package com.giftme.common.exception;

public enum ErrorCode {
    VALIDATION_ERROR,
    RESOURCE_NOT_FOUND,
    PRODUCT_NOT_FOUND,
    ORDER_NOT_FOUND,
    MEMORY_NOT_FOUND,
    CUSTOMER_NOT_FOUND,
    USER_NOT_FOUND,
    DUPLICATE_SLUG,
    DUPLICATE_EMAIL,
    DUPLICATE_PUBLIC_CODE,
    INVALID_CREDENTIALS,
    ACCOUNT_DISABLED,
    INVALID_REFRESH_TOKEN,
    INSUFFICIENT_STOCK,
    INVALID_STATUS_TRANSITION,
    ORDER_LOCKED,
    FILE_VALIDATION_ERROR,
    ACCESS_DENIED,
    AUTHENTICATION_REQUIRED,
    RATE_LIMIT_EXCEEDED,
    INTERNAL_ERROR
}
